// Copyright The Linux Foundation and each contributor to LFX.
// SPDX-License-Identifier: MIT

// Package ai contains AIAdapter implementations selected at startup via
// AI_SOURCE. The fake adapter is deterministic (same input -> same output,
// no network, no credentials) and is selected by AI_SOURCE=fake — intended
// for local dev, CI, and the prompt-eval harness. AI_SOURCE defaults to
// "fake" when unset so a fresh install boots without LiteLLM credentials;
// operators must explicitly set AI_SOURCE=live to enable the live adapter
// (see cmd/committee-api/service/providers.go).
package ai

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"sort"
	"strings"

	"github.com/linuxfoundation/lfx-v2-committee-service/internal/domain/port"
)

// FakeAdapter is a deterministic AIAdapter implementation. It does not perform
// any network I/O and never reads time.Now() or rand. Identical input always
// produces identical output.
type FakeAdapter struct{}

// NewFakeAdapter returns a new deterministic fake AI adapter.
func NewFakeAdapter() *FakeAdapter {
	return &FakeAdapter{}
}

// GenerateWeeklyBrief implements port.AIAdapter. The output always satisfies
// the schema contract: >=1 ClaimID, >=1 SourceRef, BriefText with >=2 paragraphs.
func (a *FakeAdapter) GenerateWeeklyBrief(_ context.Context, in port.WeeklyBriefInput) (port.WeeklyBrief, error) {
	// Build claim IDs deterministically. If the caller supplies claims, reuse
	// their IDs (sorted) so we are stable regardless of input ordering. If the
	// caller supplies none, synthesise a single "claim-1" derived from a hash
	// of the input so we still satisfy the >=1 constraint deterministically.
	claimIDs := make([]string, 0, len(in.Claims)+1)
	sourceRefs := make([]port.SourceRef, 0)
	seenSources := map[string]struct{}{}

	for _, c := range in.Claims {
		claimIDs = append(claimIDs, c.ID)
		for _, s := range c.Sources {
			key := s.Type + "\x00" + s.ID
			if _, ok := seenSources[key]; ok {
				continue
			}
			seenSources[key] = struct{}{}
			sourceRefs = append(sourceRefs, s)
		}
	}
	sort.Strings(claimIDs)
	sort.Slice(sourceRefs, func(i, j int) bool {
		if sourceRefs[i].Type != sourceRefs[j].Type {
			return sourceRefs[i].Type < sourceRefs[j].Type
		}
		return sourceRefs[i].ID < sourceRefs[j].ID
	})

	if len(claimIDs) == 0 {
		claimIDs = []string{"claim-1"}
	}
	if len(sourceRefs) == 0 {
		// Derive a deterministic synthetic source from the input hash so the
		// fake adapter is still usable when the caller has no evidence to pass.
		sourceRefs = []port.SourceRef{{
			Type: "fake",
			ID:   "source-" + inputDigest(in)[:12],
		}}
	}

	committee := in.CommitteeName
	if committee == "" {
		committee = "this committee"
	}
	project := in.ProjectName
	if project == "" {
		project = "the project"
	}
	window := strings.TrimSpace(in.PeriodStart + " to " + in.PeriodEnd)
	if window == "to" {
		window = "the reporting window"
	}

	var firstPara strings.Builder
	fmt.Fprintf(&firstPara,
		"Weekly brief for %s under %s covering %s. This brief is generated by the deterministic fake AI adapter and grounds on %d claim(s) drawn from %d source(s).",
		committee, project, window, len(claimIDs), len(sourceRefs),
	)

	var secondPara strings.Builder
	secondPara.WriteString("Highlights: ")
	if len(in.Claims) > 0 {
		summaries := make([]string, 0, len(in.Claims))
		for _, c := range in.Claims {
			s := strings.TrimSpace(c.Summary)
			if s == "" {
				s = c.ID
			}
			summaries = append(summaries, s)
		}
		sort.Strings(summaries)
		secondPara.WriteString(strings.Join(summaries, "; "))
		secondPara.WriteString(".")
	} else {
		secondPara.WriteString("no claims were supplied for this period, so this brief is a placeholder with stable identifiers for downstream tests.")
	}

	brief := firstPara.String() + "\n\n" + secondPara.String()

	out := port.WeeklyBrief{
		ClaimIDs:   claimIDs,
		SourceRefs: sourceRefs,
		BriefText:  brief,
	}
	return out, nil
}

// inputDigest produces a stable, content-addressed hex digest of the input.
// Used to derive synthetic IDs that are deterministic but distinct per input.
func inputDigest(in port.WeeklyBriefInput) string {
	h := sha256.New()
	_, _ = fmt.Fprintf(h, "%s\x00%s\x00%s\x00%s\x00%s",
		in.CommitteeID, in.CommitteeName, in.ProjectName, in.PeriodStart, in.PeriodEnd)
	// Iterate claims in a stable order: sort by ID first.
	claims := append([]port.ClaimEvidence(nil), in.Claims...)
	sort.Slice(claims, func(i, j int) bool { return claims[i].ID < claims[j].ID })
	for _, c := range claims {
		_, _ = fmt.Fprintf(h, "\x01%s\x00%s", c.ID, c.Summary)
		sources := append([]port.SourceRef(nil), c.Sources...)
		sort.Slice(sources, func(i, j int) bool {
			if sources[i].Type != sources[j].Type {
				return sources[i].Type < sources[j].Type
			}
			return sources[i].ID < sources[j].ID
		})
		for _, s := range sources {
			_, _ = fmt.Fprintf(h, "\x02%s\x00%s", s.Type, s.ID)
		}
	}
	return hex.EncodeToString(h.Sum(nil))
}
